services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - ./site:/var/www/html
    ports:
      - "81:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: dictionary_app
      

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1


volumes:
  mysql:
